### ISSUE TITLE
SteemConnect?

### ISSUE THREAD

**Issue by fervi** [davidkevork/steemphp#2]
I see that the new version is announced. Unfortunately, it will probably be based on SteemJS - that is, get the password and user login and execute commands. It does not seem very safe, but I do not know any other way.

The alternative is to use SteemConnect for this. Do you think this could be implemented in PHP?

**Comment by davidkevork** [comment]
@fervi I will add both, SteemJS and SteemConnect so that you can use whichever one you want

**Comment by fervi** [comment]
Ok, thanks
