### ISSUE TITLE
Posting Articles/Content using the API... 

### ISSUE THREAD

**Issue by BlockChainBobC** [davidkevork/steemphp#4]
Hey is it currently possible to use this api to post content to STEEM in the same way there is a facebook api that can post content to the facebook newsfeed?

**Comment by davidkevork** [comment]
@BCwhoLikesPHP i am working on posting content and it will be available within few weeks

**Comment by mahendrabvala** [comment]
@davidkevork - Please let us know if it is available. Thank you!

**Comment by danman1234** [comment]
Is it still not availabel? How to POST on steem with PHP?

**Comment by amainz** [comment]
@davidkevork I am still checking if you great API gets the posting, voting etc additions. Do you still plan to work on this? Would be great to hear from you.

**Comment by davidkevork** [comment]
@amainz I won't be working on the API anymore, but if you would like to continue and develop it contact me on steemit.chat @davidk
