### ISSUE TITLE
Your requirements could not be resolved to an installable set of packages.

### ISSUE THREAD

**Issue by ghost** [davidkevork/steemphp#6]
I tried to add the library to my project but I keep getting the following error:

 Installation request for davidkevork/steemphp dev-master -> satisfiable by davidkevork/steemphp[dev-master].
    - davidkevork/steemphp dev-master requires bitwasp/bitcoin 0.0.33.x-dev -> satisfiable by bitwasp/bitcoin[0.0.33.x-dev] but these conflict with your requirements or minimum-stability.

**Comment by davidkevork** [comment]
You have already installed the library but you are trying to reinstall which is why that error is being shown
