### ISSUE TITLE
Install error terminal 

### ISSUE THREAD

**Issue by brainkode** [davidkevork/steemphp#9]
Problem 1
    - The requested package bitwasp/bitcoin (locked at v0.0.33.0, required as ^0.0.35) is satisfiable by bitwasp/bitcoin[v0.0.33.0] but these conflict with your requirements or minimum-stability.
  Problem 2
    - Installation request for davidkevork/steemphp dev-master -> satisfiable by davidkevork/steemphp[dev-master].
    - davidkevork/steemphp dev-master requires bitwasp/bitcoin 0.0.33.x-dev -> satisfiable by bitwasp/bitcoin[0.0.33.x-dev] but these conflict with your requirements or minimum-stability.

**Comment by davidkevork** [comment]
This library is no more maintained. To fix the issue fork this library and update composer.json line 15 with newer version of bitwasp/bitcoin library.
